### ISSUE TITLE
[Question] Does this fix the listener issue for vuejs and materialize's select?

### ISSUE THREAD

**Issue by austinkregel** [aguegu/vue-materializecss#1]
A little bit ago, I tried making an app for work that uses both materialize and VueJS, but soon noted the select element wouldn't update vuejs when choosing from materialize's select element. I made a [question on SO](http://stackoverflow.com/questions/34444382/jquery-and-materialize-not-updating-vuejs-select-value/34724759) and I got really hacky answers. 

I never had it working 100% so I abandoned that setup and started using bootstrap and vuejs.

**Comment by aguegu** [comment]
Haha, if you have try both materializecss and vuejs, we have been on the same track.

I abandoned materializecss when I found [mdl](http://getmdl.io/). I have been trying to build a SPA with mdl and vuejs in my side project for over two months(slowly growing). It turns out well through. 

I may trun back to bootstrap, if it release a production-ready 4.0.

Regarding your answer, I have post my suggestion.
